# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install
      - run: ls -la
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn test
      - run: yarn build
      - run: ls -la build
      - persist_to_workspace:
          root: .
          paths: 
            - build/*
  
  brotli:
    # docker:
    #   - image: circleci/node:10
    docker:
      - image: google/cloud-sdk
    steps:
      # - checkout
      # - attach_workspace:
      #     at: .
      - run: sudo apt update && sudo apt upgrade -y
      - run: sudo apt install brotli
      # - run: bash script/package.sh
      # - run: ls -la build


workflows:
  version: 2
  workflow:
    jobs:
      - build
      - brotli:
          requires:
            - build

